name:                ccompiler
version:             0.1.0.0
github:              "githubuser/ccompiler"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ccompiler#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs:
    - src/
    #- src/Preprocessor/
  exposed-modules:
    # Miscellaneous utilities
    - AbstractSyntaxTree
    - ASTEquipped
    - CustomCombinators
    - Auditable
    # Preprocessor specific modules
    - Preprocessor.CharacterConstant
    - Preprocessor.Comma
    - Preprocessor.ConstantExpression
    - Preprocessor.DefineDirective
    - Preprocessor.EndIfLine
    - Preprocessor.ErrorDirective
    - Preprocessor.Group
    - Preprocessor.Identifier
    - Preprocessor.IdentifierList
    - Preprocessor.IncludeDirective
    - Preprocessor.IntegerConstant
    - Preprocessor.LParen
    - Preprocessor.LineDirective
    - Preprocessor.NewLine
    - Preprocessor.NonDirectiveLine
    - Preprocessor.NullDirective
    - Preprocessor.Octothorpe
    - Preprocessor.PPTokens
    - Preprocessor.PragmaDirective
    - Preprocessor.PreprocessingParser
    - Preprocessor.Preprocessor
    - Preprocessor.ReplacementList
    - Preprocessor.StringLiteral
    - Preprocessor.TextLine
    - Preprocessor.UndefDirective
    # Lexer modules (preprocessing lexer)
    - Lexer.Lexer
    - Lexer.PreprocessingToken
    # Compiler Proper specific modules
    - Compiler.Parser.TranslationUnit
    - Compiler.SymbolTable.SymbolTable
    # Character Token Parsers
    - CharTokenParsers.Constants.CharacterConstants.CharacterConstant
    - CharTokenParsers.Constants.Constant
    - CharTokenParsers.Constants.EnumerationConstants.EnumerationConstant
    - CharTokenParsers.Constants.IntegerConstants.IntegerConstant
    - CharTokenParsers.HeaderNames.HeaderName
    - CharTokenParsers.Identifiers.Identifier
    - CharTokenParsers.PPNumbers.PPNumber
    - CharTokenParsers.PrimitiveParsers.Digit
    - CharTokenParsers.PrimitiveParsers.IdentifierNonDigit
    # TODO: remove CharTokenParsers.PrimitiveParsers.IntegerConstant module from the repo/project
    # Use CharTokenParsers.Constants.IntegerConstants.IntegerConstant instead
    - CharTokenParsers.PrimitiveParsers.IntegerConstant
    - CharTokenParsers.PrimitiveParsers.NonDigit
    - CharTokenParsers.PrimitiveParsers.EscapeSequence
    - CharTokenParsers.PrimitiveParsers.OctalDigit
    - CharTokenParsers.PrimitiveParsers.UniversalCharacterName
    - CharTokenParsers.Punctuators.Punctuator
    - CharTokenParsers.StringLiterals.StringLiteral

executables:
  preprocessor:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ccompiler

tests:
  ccompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ccompiler
